"""update parking models for public sessions

Revision ID: e136fd07c90a
Revises: 445972fdabbb
Create Date: 2025-10-29 15:28:36.897711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e136fd07c90a'
down_revision: Union[str, None] = '445972fdabbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('space_number', sa.String(length=20), nullable=False),
    sa.Column('space_type', sa.String(length=50), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_spaces_id'), 'parking_spaces', ['id'], unique=False)
    op.create_index(op.f('ix_parking_spaces_lot_id'), 'parking_spaces', ['lot_id'], unique=False)
    op.create_index('ix_parking_spaces_lot_number', 'parking_spaces', ['lot_id', 'space_number'], unique=True)
    op.add_column('parking_lots', sa.Column('location_address', sa.String(length=500), nullable=True))
    op.alter_column('parking_lots', 'venue_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('parking_sessions', sa.Column('lot_id', sa.UUID(), nullable=False))
    op.add_column('parking_sessions', sa.Column('space_id', sa.UUID(), nullable=True))
    op.add_column('parking_sessions', sa.Column('access_code', sa.String(length=20), nullable=False))
    op.add_column('parking_sessions', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('parking_sessions', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('parking_sessions', sa.Column('last_notification_sent', sa.DateTime(), nullable=True))
    op.alter_column('parking_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_parking_sessions_parking_lot_id', table_name='parking_sessions')
    op.drop_index('ix_parking_sessions_lot_status', table_name='parking_sessions')
    op.create_index('ix_parking_sessions_lot_status', 'parking_sessions', ['lot_id', 'status'], unique=False)
    op.create_index('ix_parking_sessions_access_code', 'parking_sessions', ['access_code'], unique=False)
    op.create_index(op.f('ix_parking_sessions_lot_id'), 'parking_sessions', ['lot_id'], unique=False)
    op.create_index(op.f('ix_parking_sessions_space_id'), 'parking_sessions', ['space_id'], unique=False)
    op.drop_constraint('parking_sessions_parking_lot_id_fkey', 'parking_sessions', type_='foreignkey')
    op.drop_constraint('parking_sessions_user_id_fkey', 'parking_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'parking_sessions', 'parking_spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'parking_sessions', 'parking_lots', ['lot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'parking_sessions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('parking_sessions', 'parking_lot_id')
    op.drop_column('parking_sessions', 'space_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_sessions', sa.Column('space_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('parking_sessions', sa.Column('parking_lot_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parking_sessions', type_='foreignkey')
    op.drop_constraint(None, 'parking_sessions', type_='foreignkey')
    op.drop_constraint(None, 'parking_sessions', type_='foreignkey')
    op.create_foreign_key('parking_sessions_user_id_fkey', 'parking_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('parking_sessions_parking_lot_id_fkey', 'parking_sessions', 'parking_lots', ['parking_lot_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_parking_sessions_space_id'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_lot_id'), table_name='parking_sessions')
    op.drop_index('ix_parking_sessions_access_code', table_name='parking_sessions')
    op.drop_index('ix_parking_sessions_lot_status', table_name='parking_sessions')
    op.create_index('ix_parking_sessions_lot_status', 'parking_sessions', ['parking_lot_id', 'status'], unique=False)
    op.create_index('ix_parking_sessions_parking_lot_id', 'parking_sessions', ['parking_lot_id'], unique=False)
    op.alter_column('parking_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('parking_sessions', 'last_notification_sent')
    op.drop_column('parking_sessions', 'contact_phone')
    op.drop_column('parking_sessions', 'contact_email')
    op.drop_column('parking_sessions', 'access_code')
    op.drop_column('parking_sessions', 'space_id')
    op.drop_column('parking_sessions', 'lot_id')
    op.alter_column('parking_lots', 'venue_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('parking_lots', 'location_address')
    op.drop_index('ix_parking_spaces_lot_number', table_name='parking_spaces')
    op.drop_index(op.f('ix_parking_spaces_lot_id'), table_name='parking_spaces')
    op.drop_index(op.f('ix_parking_spaces_id'), table_name='parking_spaces')
    op.drop_table('parking_spaces')
    # ### end Alembic commands ###
